apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wls-ms1
  namespace: wls1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wls-ms1
  template:
    metadata:
      labels:
        app: wls-ms1
        tenant: t1
    spec:
      serviceAccountName: wls
      containers:
      - name: wls-ms1
        image: phx.ocir.io/oicpaas1/sumagant/wls-domain:12.2.1.3
        imagePullPolicy: Always
        env:
        #- name: ADMIN_HOST
        #  value: "10.244.0.243"
        - name: ADMIN_PORT
          value: "7001"
        - name: ADMIN_PASSWORD
          value: "welcome1"
        - name: MS_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        #- name: MS_NAME
        #  value: "wls-ms1"
        #- name: NM_NAME
        #  value: nm_ms1
        - name: MS_PORT
          value: "8001"
        - name: NM_PORT
          value: "5556"
        command: ["createServer.sh"]
      imagePullSecrets:
      - name: k8s-pull
---
apiVersion: v1
kind: Service
metadata:
  name: ms1
  namespace: wls1
spec:
  selector:
    app: wls-ms1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001

