apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wls-ms
  namespace: wls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wls-ms
  template:
    metadata:
      labels:
        app: wls-ms
        tenant: t1
    spec:
      serviceAccountName: wls
      containers:
      - name: wls-ms
        image: phx.ocir.io/oicpaas1/sumagant/wls-domain:12.2.1.3
        imagePullPolicy: Always
        env:
        - name: ADMIN_PORT
          value: "7001"
        - name: ADMIN_PASSWORD
          value: "welcome1"
        - name: MS_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MS_PORT
          value: "8001"
        - name: NM_PORT
          value: "5556"
        command: ["createServer.sh"]
      imagePullSecrets:
      - name: k8s-pull
---
apiVersion: v1
kind: Service
metadata:
  name: ms
  namespace: wls
spec:
  selector:
    app: wls-ms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001

